### ISSUE TITLE
Overseas Trade Statistics (CN8): Trade Partner Geography code list mismatch

### ISSUE THREAD

**Issue by jennet** [Swirrl/ons-data-export#45] opened 2020-04-29 09:18 UTC
Dataset: `hmrc_ots_cn8`
Component: `http://gss-data.org.uk/data/gss_data/trade/hmrc_ots_cn8/component/hmrc_partner_geography`
Dimension: `http://gss-data.org.uk/def/dimension/trade-partner-geography`
Configured codeList: `http://gss-data.org.uk/def/concept-scheme/ons-trade-areas-cord`

[see config](https://github.com/GSS-Cogs/family-trade/blob/master/reference/components.csv#L15)

Observation values in that dataset actually come from code list: `http://gss-data.org.uk/def/concept-scheme/hmrc-geographies`

This means that the filter modal will load up concepts from the `ons-trade-areas-cord` code list, but all will be greyed out as there are no corresponding values in the data.

**Comment by RedWalters** [comment] 2020-05-01 09:37
This issue should be fixed, most recent version in PMD4 is out of date. PMD3 version times out (SORRY error screen) but not sure of the cause

**Closed** 2020-05-04 15:26 UTC
Labels: fao-ons
